### ISSUE TITLE
Choosing Dataset

### ISSUE THREAD

**Issue by ttchen123** [HGYll77/Final-Project#4]
Which dataset should we use?

Do we need any other dataset?

**Comment by HGYll77** [comment]
We use the WA COVID-19 cases of hospitalizations and deaths.

**Comment by winfredgu** [comment]
We will also use data about total population of the counties in WA to calculate relative data about COVID-19

resources:
https://ofm.wa.gov/washington-data-research/population-demographics/population-estimates/april-1-official-population-estimates
